"""Generated by tools/gen_setup_payload.py -- do not edit by hand.

Everything the Setup button needs to build a gateway from nothing. Payloads are
zlib-compressed and base64-encoded; call the accessor rather than touching the blobs.
"""
import base64
import json
import zlib


def _blob(b64):
    return zlib.decompress(base64.b64decode(b64))


def _json(b64):
    return json.loads(_blob(b64))

_PROVIDER = (
    "eNqdj7FuwzAMRP+Fc74gmwt3K5IiyVZ0YOxTIJSWDJFKagT+91IZsqcbceS7O95pLjlEAW3vxCL59sbDjwtC28Ci2BASnwUn"
    "vhwQUJAGHC0XB6xUX9sy+0zHU7fru0NP64YUZjFdtHmOCFzFejbWXMuAHU/t/v2Xp1mg5AFjtE+UKarGnB6UYqgl2vKBK8SV"
    "r+9nUCeyDy2lgMd9kuVZtAn/8LmyVDinUa1957vW9swKL3dzHC+7rusfAkZ6sw=="
)


def tagProvider():
    return _json(_PROVIDER)


_HISTORIAN = (
    "eNpNjrsOwjAMRf/FcwZgYOjGUKlLQaIgxOi2LrJIk5C44lH130moQEzXujryPSM4bzvWBNkI8nQxobrpgoNYz2hgUhBIhM0l"
    "JKRFwRpDwvIH9k5TAAUOvbCwNQkhg7WmFjLxAymwTrjnVyo61OG/ObFp7b2ixpo2fl8v4lbsIVvOx9GwxB7K3fZQJBPnBxNN"
    "0gpeZi7mFzvnm32U+e1/5pK/oKZy0MJOM3nIVgrEY3OtGpotp+kNs9VbNw=="
)


def historian():
    return _json(_HISTORIAN)


_DEVICE = (
    "eNoVi7EKwzAMBf9FcwZ3zdylQ6EkX6CmL0Ygx0ZWAiH43+NOx8HdRcXyKgoaL/KzdNLHcjROib+KWdKu7NmeOGQBtYEq3GWL"
    "9X8oIi/nO//6t7JWDGQoYKfRbe/mkvDaHHawTuw9e4QQWrsBXDcrOQ=="
)


def device():
    return _json(_DEVICE)


_INSTRUCTIONS = (
    "eNqtV8tu2zAQvPcrBJ9SQKDF5UPSMY8CDVqgRmK06FGxmVaoLRmUlMB/35VoNwxi0lSji3SwPNiZnZ0ll+VWRbdVq/RTsYmj"
    "K10/NypaFO3vOPpebDoV3dedXqk4uinaIlrud+rDLJnFsy+L2/nXslLN8GTz67rcLNV2p3TRdlrhF6u6wV8uGCNZHkcSCEAc"
    "QZYkJImjVnfqI350U3cPGzU7hSnmC12vu1Vb1tVd0faQuqjW9fYCRA8BMhAonV8iyJNa1M9Kv6AwZkphIrgkORkSzO9Ug6Ir"
    "WGjVNEaxIz1IiGRIEFIiWGBhbv0FERL1T4YXiBH6v4/sZanfcpPIreckBfYwrA7mlcpIBIwTDoHKXxUt+n1/XeyKVdnuX6SC"
    "gRA1vCA/x2/7UKqqfS36v7qM2/ElA8V2V8XsqmRw/6gbkuYWJPbTD3mv2m63xKB44UeHCeyfMlB0Xz4wNuRDmgWobmM68wEG"
    "qVggEPdoD7b26Yig+FZu3tqVpvlgCJpJQkON4UACwlJEOiCOiZyTgP8ROuAoTVAis94dGRFZYAdOI0lB+EDSkA1CcpqCDz0U"
    "wUvDbQphm4KPGMiptgdzKW8UP+oWZC+vKTglrM8xnhGggaU5G8CMXsHjPZVafDIk6leLMpLyfoTMKI2RHyYRX57ppgEC3L2U"
    "Bk6BF/AABBjeY5e5I4RGr3PqGAXOSZr3IWTCKKi06QznJXkgd+yvE/B6v9qo13sXSC834ePcAO/wwo9a/7mtcKZXCGHpm5gQ"
    "hPDTpO+E2rtH0oOZRmxZZ9ZIs7CDw/60iQ5rmuYYXeL8UfBzty3XZlUcENCF+H+OR/BAMzsJ0YEQBBPytH781HIfXKid7eqc"
    "NIeOQRa8B91LmtpL+tyt81Ol9K/9T9Ug2LqwGoiJnmMH8Q4beNKVnpK4XdK5OLnqHh/tHMrsy8mYXQWTbKrUM79y8BPeMJOx"
    "ByI3prkOSHM5OHtFsa3qxkSj8iFnZOo+zf8FPNb1jQ=="
)


def instructions():
    return _blob(_INSTRUCTIONS)


_TAGS = (
    "eNrtXW1P4zgQ/itW0UpwgpJk+8Jx2g+F5W6rg91qYQ/dUT64ybT1kcSV48D2EP/9nLeStknb0BfS1BKqoHbjyTyPZ+YZd7PP"
    "JY57RwZ0iU04ofaxiV1b7w+wcfxnq3ksBp3yvw61S6elu7aN0LP3glC79IhNF66py3Rol07FG3Sgt0uH0XCfOJyy4Q2x4DNg"
    "o4Ntw5tWU0YzxPwmB6uFeT+4gO18Un9zPt1dRhbcexY0rA4Bm9+ANQCGuctgahWiYzNa5IoaoT3fut3YTLB7X0jPX+ljvXwy"
    "et+gumuJ62Pv5oMPhiui5CW7lFmYX3NG7F4wf+9wb08pK+OL/RDuDIbbbVdROsp5bFx49WY4CO1scGoR/Qb3YhMMzPHrjN9N"
    "ivnJtHNbjD4SA1gwawTc9MQLG3dM8AHgzIXRsI0tGLvn5FsWSF0De4wWavYCqqBvrXP0o4GiMW/6y+H7kISwFgPHWQE7TrR6"
    "uTKTHoShhMUW5MUlffJGq1W1XEvmy0ML55sqib7eAo4EFP/iWsQgfLgsT1RFYLtIGElYMIUraRHkwzaEjoTbzD8nzoe6Cd5l"
    "ls4pc7ggbhT3APnroYkFOaUmJ4MwWywQUVKJ4oB+7Pp/5ZgvST5fIVMssIQZ04Zd4Z+NHkzQZD6RFmdDAuwtE+vQp6bvuNeJ"
    "0MWuyf/yLPdzgTIX8r00xG/OPmcBOyuagdO85Zxg7vXF+VswT3ZE+PFrbA1M+I75JDqOP/Dq7xYwQg2iv2vIuLCB9YZ/g8OB"
    "GXjpNFKdHTiC1dAldjjSKn3mLBUf/rjt5zo0pPs2/6nklrKHpi2coYvaaO3FhbcaatooXA/t3zZbB2+vMNxgh7+VGk2bV9ZK"
    "jDTnrpAW8HPAZmUNNQNlvGsJQ0doPd+V7z9jYnouMVzdM7F8EaD9gn5B+5xeEdMkzj42jC/CJmffpk/7ggSKcnDYA+4t9R+1"
    "QfDFAb5/cHDw4aRWUfzx4+i3cbcsQtkJk1Ko+Os8LvqXQYnXyZzPdOxAnomY7rJ1ljDjNxm5c423+ZVyGP/oZNEiSg/8AMgW"
    "Ex3UBwZIbAPE+zBET4LLqAPIwY8g3qIIIwEjElxApkjyDLkOlBfA+B2D+TVwd7ASXaAsJgz8BSeFQeZWk0XsXOf3JLdutPRX"
    "l6HK0kk9cyRFFz8HoHOYtRG9q2aKt1NVd6y8v2p+zWdknhIi45a+NX4n+DdRlKgLaJItqlXP3G43QYmtukidWqZgVenU/WVB"
    "vm3flw5nH764NmbDI1FJ+oyIjmF8tggi6jS60T9CEwSBgEVVpxq+JT4u/B2Q/BR1selAOELFbEYM7y7HblLgREzw99ldzPXB"
    "OVBg/X04EXNx7Y7Lg9kjHuvU7hIf4eeXkXNMoWEFq0hX0CziSPgJ/1K6cPoEKEeOlzBGDvYNEeR3uNiEwVRN0WpHiip+bhTl"
    "1P/5JzDRd7H/8jLPz5fEBicP3i6iW73Xjzk4R4xbcyYcDGx4jgdYH29ZYxMzK0599OpMb9wahcUzMOlTmIUP41OEcweU2Lzh"
    "zdNeQ+RU9AiMQP6J0NgcE3fADCZ59qKPE+MDkXKYb7efCcEgrhWhE+ITbdG0yByuneCBzEVnvk8n0qHOf5qOU7Yh6pVHaNGn"
    "8VbyitwZy+peM6GsvOEYKNHAzGx6uM1Cp+3C8Ds4nkFawvHpqoBM2OvhqkhDqUfkC8A7w/bsGGc74d4ukF/FRSAeNgFxTDFO"
    "LLr4CU2a2ZnR9av244ytiO3C+BsxN7uHxYJL7d5kg+XGTYjOG8c2is8jjMtLxGcJ9Hygzykxk7/oFiuDatXY97MWVwWNjtB5"
    "c1WBWqmmygLPuvhXD1Fg0TyBkKX6n1yi8N9uTEd8xR2bOM1k92bTbYZartoMtRlthjWmkxnSfgWieb3dgW3KI7U35BEZi1cV"
    "i98ffdmQ2f4dLBsyhS/3a1LX7QrQsitTQFBlO3Xd7dRMsrYmZe3GZW01V7K2KnXPDuueqsyyxcuyVSmEdgFk2Y4scDuyKivl"
    "wn/xoCp7GbsSq2V3eaOytipl7cZlbSVXsrYiy6Mil0cVmTp3I3VWZIOiwLtXNiiKDLJsLO9uY7kiJU8BdrDsQeXqtLYiZe3G"
    "ZW09V7K2LmVtkWVtXWbNAmAos2bRT27qsitRRFBlV2IHQJZdid3tStTlscFmtnkmWVuXsnbjslbLlazV5L7cjfSrSYFbAAyl"
    "wC26wNWkFtqFYCy7GAUEtXjPQ9JmPjD1XPzqPepaPjRpBxS8tm0P+9Xkw37f+WG/mXoRmuxFbLwXoeaqF6HK0rf4VZK6bWlE"
    "nRg3iDMw8TDhf7ORaWY3nymvFrDwV2XhLwv/iN6yWVHANCzPfXYEaHnus/0YynOfXP1zAFX2KlbVq3j5H98fDnc="
)


def tagFiles():
    return _json(_TAGS)
