#!/usr/bin/env python3
"""Bake everything the Setup button needs into each project as a script module.

The button has to be able to build a gateway from nothing: tag provider, historian,
simulator device (including its programme), and the tags themselves. None of that is
reachable from a running Perspective session unless it ships INSIDE the project, so
this generates `exchange.launchpad.payload` for OEE and for KPI.

Payloads are zlib+base64 rather than literal JSON: 150 KB of pretty-printed tag
definitions inside a .py is unreadable either way, and the compressed form survives
copy/paste and diffing without a quoting minefield.

    python3 tools/gen_setup_payload.py

Regenerate whenever live-config/ changes -- the generated modules are checked in, so a
stale payload installs a stale gateway and nothing complains.
"""
import base64
import json
import os
import shutil
import subprocess
import sys
import tempfile
import zlib

ROOT = os.path.dirname(os.path.abspath(__file__)) + "/.."
CFG = ROOT + "/live-config"

HEADER = '''"""Generated by tools/gen_setup_payload.py -- do not edit by hand.

Everything the Setup button needs to build a gateway from nothing. Payloads are
zlib-compressed and base64-encoded; call the accessor rather than touching the blobs.
"""
import base64
import json
import zlib


def _blob(b64):
    return zlib.decompress(base64.b64decode(b64))


def _json(b64):
    return json.loads(_blob(b64))

'''


def pack(obj):
    raw = json.dumps(obj, separators=(",", ":")).encode()
    return base64.b64encode(zlib.compress(raw, 9)).decode()


def pack_bytes(data):
    return base64.b64encode(zlib.compress(data, 9)).decode()


def wrap(b64, width=96):
    return "\n".join('    "%s"' % b64[i:i + width] for i in range(0, len(b64), width))


def emit(name, b64, accessor, kind="json"):
    return (
        "_%s = (\n%s\n)\n\n\n"
        "def %s():\n    return _%s(_%s)\n\n\n"
        % (name, wrap(b64), accessor, kind, name)
    )


def config_tree(*roots):
    """Pack live-config subtrees as {relative path: file text}.

    Tags go onto a gateway as CONFIG RESOURCES, not through system.tag.configure.
    The runtime API looks tidier and cost a day: configuring a subtree at the
    provider root takes the provider's other subtrees with it, so importing KPI's
    tags silently removed OEE's. Writing the resource files and running a config
    scan is what tools/install.sh has always done, and it composes -- two projects
    can each install their own tags without touching the other's.
    """
    out = {}
    for root in roots:
        base = os.path.join(CFG, root)
        walked = [(os.path.dirname(base), [os.path.basename(base)])] if os.path.isfile(base) \
            else [(dp, fs) for dp, _, fs in os.walk(base)]
        for dirpath, files in walked:
            for f in files:
                full = os.path.join(dirpath, f)
                rel = os.path.relpath(full, CFG)
                text = open(full).read()
                if f in ("resource.json", "unary-resource.json"):
                    # a stale signature makes the scan skip the resource in silence
                    d = json.loads(text)
                    attrs = d.get("attributes", d)
                    attrs.pop("lastModificationSignature", None)
                    attrs["lastModification"] = {"actor": "launchpad-setup",
                                                 "timestamp": "2026-01-01T00:00:00Z"}
                    text = json.dumps(d, indent=2)
                out[rel] = text
    return out


def tag_exports():
    """Reuse the exporter that already builds the Designer-importable shape."""
    tmp = tempfile.mkdtemp()
    try:
        subprocess.check_call([sys.executable, ROOT + "/tools/build_tag_exports.py", tmp],
                              stdout=subprocess.DEVNULL)
        # the exporter writes one subdirectory per package (oee/, kpi/)
        out = {}
        for dirpath, _, files in os.walk(tmp):
            for f in files:
                with open(os.path.join(dirpath, f), "rb") as fh:
                    out[f] = fh.read()
        return out
    finally:
        shutil.rmtree(tmp)


def main():
    exports = tag_exports()
    provider = json.load(open(CFG + "/tag-provider/launchpad/config.json"))
    historian = json.load(open(CFG + "/historian-provider/launchpad/config.json"))
    device = json.load(open(CFG + "/device/Launchpad/config.json"))
    instructions = open(CFG + "/device/Launchpad/instructions.csv", "rb").read()

    common = HEADER
    common += emit("PROVIDER", pack(provider), "tagProvider")
    common += emit("HISTORIAN", pack(historian), "historian")
    common += emit("DEVICE", pack(device), "device")
    common += emit("INSTRUCTIONS", pack_bytes(instructions), "instructions", kind="blob")

    projects = {
        # Deliberately NOT tag-definition/launchpad/unary-resource.json: that resource
        # belongs to the PROVIDER ROOT, and the gateway writes it when the provider is
        # created. Shipping a baked copy means the second project to install overwrites
        # the live one, and the whole subtree then fails to reconcile -- which looks
        # like "the scan does not pick up my tags" and is really "I clobbered the
        # folder resource the provider was using".
        "OEE": [("TAGS", config_tree("tag-definition/launchpad/OEE",
                                     "tag-type-definition/launchpad"), "tagFiles")],
        "KPI": [("TAGS", config_tree("tag-definition/launchpad/KPI"), "tagFiles")],
    }

    for proj, blobs in projects.items():
        body = common
        for name, obj, accessor in blobs:
            body += emit(name, pack(obj), accessor)
        dest = "%s/final/%s/ignition/script-python/exchange/launchpad/payload" % (ROOT, proj)
        os.makedirs(dest, exist_ok=True)
        with open(dest + "/code.py", "w") as fh:
            fh.write(body.rstrip() + "\n")
        res = dest + "/resource.json"
        if not os.path.exists(res):
            json.dump({"scope": "G", "version": 1, "restricted": False, "overridable": True,
                       "files": ["code.py"],
                       "attributes": {"lastModification": {"actor": "external",
                                                           "timestamp": "1970-01-01T00:00:00Z"}}},
                      open(res, "w"), indent=2)
        print("  %-3s payload %6d bytes" % (proj, os.path.getsize(dest + "/code.py")))


if __name__ == "__main__":
    main()
